Performance increase
lucaong/minisearch pull request #122
Opened 2022-02-15 12:54 UTC by rolftimmermans

Hi there!

First of all thanks for creating this library. We are using it in production on a website with published guidelines on hazardous substances, created in collaboration between ministries and other government bodies in The Netherlands.

Although we've been quite happy with the performance (great job!), our profiling shows that there is some improvement to be made with regards to the creation of temporary objects. This is mostly due to using plain objects instead of ES6 [Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). 

Objects are great for storing a fixed number of keys, but less great for a larger number of keys, for addition/deletion, or for iterating over them.

In particular the following pattern showed up in a few places:

```
Object.entries(object).forEach(([key, value]) => {
  //
})
```

This has some issues:
* It causes at least one allocation for the array returned by `Object.entries()`.
* It causes an allocation for the closure passed into `forEach()`.
* Iterating with `for ... of ... ` is almost always faster (in part due to the allocations).
* Unnecessary temporary objects cause pressure on the garbage collector.

I made the following changes:
* Most occurrences of objects are replaced with Maps.
* Functions that take closures are mostly replaced with loops.
* Some duplicate read/write operations were prevented.
* The internal IDs of fields are now numbers. Because field IDs are consecutive and do not change, we can store the field data in arrays with the ID as the index.
* Document short IDs are now numbers. There is no need to transform them into strings, which saves a small amount of space and time during indexing.

All of this mostly gave a performance boost. Using the benchmarks in the project on my laptop with Node v17.2.0 (which should be representative for a modern version of Chrome):
* Indexing is at least 4x faster.
* Combined search is about 2x faster.

However, **nothing comes for free**... Because the internal structure is no longer 1-1 serialisable to and from JSON, that operation becomes more expensive. Loading an index from JSON is about 30% **slower**, and is also much more complicated.

Finally, ES6 Maps might not be supported in very old browsers. However, their support is slightly better than that of Unicode Regexes, which are also used in the project.

I'd love to hear your thoughts on this PR. Let me know if there is anything I should clarify!

### Before
```
Index size: 13497 terms, 14097 documents, ~17.49MB in memory, 2.37MB serialized.

Fuzzy search:
=============
  * SearchableMap#fuzzyGet("virtute", 1) x 24,029 ops/sec ±0.23% (100 runs sampled)
  * SearchableMap#fuzzyGet("virtu", 2) x 1,918 ops/sec ±0.23% (99 runs sampled)
  * SearchableMap#fuzzyGet("virtu", 3) x 385 ops/sec ±0.42% (95 runs sampled)

Prefix search:
==============
  * Array.from(SearchableMap#atPrefix("vir")) x 381,810 ops/sec ±0.13% (100 runs sampled)
  * Array.from(SearchableMap#atPrefix("virtut")) x 592,633 ops/sec ±0.16% (98 runs sampled)

Exact search:
=============
  * SearchableMap#get("virtute") x 858,585 ops/sec ±0.08% (99 runs sampled)

Indexing:
=========
  * MiniSearch#addAll(documents) x 3.76 ops/sec ±3.47% (14 runs sampled)

Combined search:
================
  * MiniSearch#search("virtute e conoscienza") x 46.38 ops/sec ±4.34% (63 runs sampled)

Search filtering:
=================
  * MiniSearch#search("virtu", { filter: ... }) x 9,135 ops/sec ±4.19% (88 runs sampled)

Auto suggestion:
================
  * MiniSearch#autoSuggest("virtute cano") x 33,132 ops/sec ±3.56% (91 runs sampled)
  * MiniSearch#autoSuggest("virtue conoscienza", { fuzzy: 0.2 }) x 181,194 ops/sec ±1.20% (101 runs sampled)

Load index:
===========
  * MiniSearch.loadJSON(json, options) x 33.50 ops/sec ±2.46% (60 runs sampled)
```

### After
```
Index size: 13497 terms, 14097 documents, ~16.01MB in memory, 2.49MB serialized.

Fuzzy search:
=============
  * SearchableMap#fuzzyGet("virtute", 1) x 27,119 ops/sec ±0.19% (99 runs sampled)
  * SearchableMap#fuzzyGet("virtu", 2) x 2,253 ops/sec ±0.21% (99 runs sampled)
  * SearchableMap#fuzzyGet("virtu", 3) x 434 ops/sec ±0.38% (92 runs sampled)

Prefix search:
==============
  * Array.from(SearchableMap#atPrefix("vir")) x 446,460 ops/sec ±0.22% (101 runs sampled)
  * Array.from(SearchableMap#atPrefix("virtut")) x 988,842 ops/sec ±0.27% (100 runs sampled)

Exact search:
=============
  * SearchableMap#get("virtute") x 1,823,572 ops/sec ±0.33% (94 runs sampled)

Indexing:
=========
  * MiniSearch#addAll(documents) x 12.09 ops/sec ±2.44% (35 runs sampled)

Combined search:
================
  * MiniSearch#search("virtute e conoscienza") x 91.87 ops/sec ±3.24% (69 runs sampled)

Search filtering:
=================
  * MiniSearch#search("virtu", { filter: ... }) x 18,009 ops/sec ±2.99% (83 runs sampled)

Auto suggestion:
================
  * MiniSearch#autoSuggest("virtute cano") x 58,476 ops/sec ±2.87% (87 runs sampled)
  * MiniSearch#autoSuggest("virtue conoscienza", { fuzzy: 0.2 }) x 327,262 ops/sec ±1.24% (98 runs sampled)

Load index:
===========
  * MiniSearch.loadJSON(json, options) x 23.24 ops/sec ±3.82% (43 runs sampled)
```

2022-02-15 13:13 UTC, rolftimmermans commented
Some things I did not do:
* Measure the impact changing the data structure in the leaf nodes of the radix tree. I think changing the structure to a sparse array could be beneficial.
* Benchmark or improve performance of document removal. It is unlikely to be worse, but it could probably be improved.
* Spend much time on improving the performance of fuzzy search, which is seems to be the largest bottleneck for (our) search performance.

2022-02-16 10:05 UTC, lucaong commented
Hi @rolftimmermans ,
thanks a lot for this outstanding contribution! It makes total sense, and improves performance by a meaningful amount, so I am willing to sacrifice some "functional beauty" as long as the code is still clear.

Allow me some time to review the PR, but I am most likely going to merge it. One question as I approach the review: does turning field IDs to number makes serialized indexes created with a previous version incompatible with this version? I think not, but I only skimmed through the code so far. Asking so I know how to bump the semantic version.

Regarding the slower de-serialization of the index, I think it is a good trade off. As the indexing is now faster, more use-cases can do without the serialization. Moreover, I am planning some breaking changes to the serialization logic in the next major release, which will make this irrelevant.

I am going to elaborate on this, in case you want to provide your opinion. The problems I see with the current serialization logic are:

  - It is very tightly coupled to the internal representation of the index (as you saw in your PR). This makes it fast, but also provides a lot of friction on improving to the internal data structures, as most changes would be breaking changes.
  - Currently the document IDs are mapped to short IDs, and the same happens with the fields. This optimization keeps the serialized index smaller, but I think it's not worth. Avoiding to map the document IDs to short IDs would make the code simpler, possibly improve performance slightly, and the in-memory index might even be smaller, as the strings would be probably pointed to in memory and not duplicated (this should be validated with a benchmark). The JSON index could get larger, because of the repetition of possibly long document IDs, but JSON is usually gzipped by the web server, making this irrelevant for transfer speed.
  - As it is currently implemented, de-serialization cannot be done asynchronously. It would be great to have something similar to `addAllAsync` but for index de-serialization. If such an option was present, a slower de-serialization would be tolerable, as it would not block the UI. In most cases it would also be an improvement for end users, because usually one does not interact with the search immediately, so async de-serialization is likely to be completed by the time the user starts interacting with the search.

Therefore, for the future I am planning to serialize the posting lists (a data structure associating a tokenized term to the list of fields/documents it appears in). The bulk of the serialized structure could at that point be an array of terms to postings, so the deserialization logic could work like `addAllAsync` and leave pauses for the main thread to paint the UI.

On the topic of improving performance of fuzzy search, the best chance I see is to re-implement the [`fuzzySearch`](https://github.com/lucaong/minisearch/blob/9208f91fab9a71c24578da6bf11834a318c342ec/src/SearchableMap/fuzzySearch.ts#L33) to use [this algorithm](http://stevehanov.ca/blog/?id=114) instead of the current one. I suspect that this would get it closer to the theoretical optimum of calculating edit distance on tries, and it is not too hard to implement given the right amount of time.

2022-02-16 10:19 UTC, rolftimmermans commented
Thank you for the detailed response! 

> One question as I approach the review: does turning field IDs to number makes serialized indexes created with a previous version incompatible with this version? I think not, but I only skimmed through the code so far. Asking so I know how to bump the semantic version.

I don't think the change from string to number is a breaking change, because the IDs are still serialised as string keys. However, there **are** breaking changes in the serialisation format in this PR: the field lengths now stored in arrays. This is possible because the IDs are numeric and sequential. This is a win, because arrays are pretty much unbeatable in lookup performance... 

On the topic of numeric IDs: if you keep the numeric short document IDs, it will be possible to change some internal data structures to use arrays instead of Maps. Did I say arrays were great for that? :) I have not gone as far now, but I wouldn't personally get rid of the step from original string ID to short numeric ID without giving this some additional thought and/or testing. (One challenge to address here is that to keep IDs reasonably sequential, removing a document requires some additional bookkeeping.)

To elaborate on this; our app also uses a mapping from original string document ID to (sequential) numeric IDs. This enables us to create [bit vectors](https://en.wikipedia.org/wiki/Bit_array) that indicate the membership of a document in some arbitrary group (like a label, category or tag). Bit vectors are compact and enable extremely fast union/intersection operations. This forms the basis of filtering functionality which complements Minisearch. All of this would be impossible with the original string IDs.

2022-02-16 10:49 UTC, lucaong commented
Thank you @rolftimmermans for your input. While the previous mapping to short string IDs was probably unnecessary, mapping to integers indeed provides interesting options that I did not consider before.

Regarding the bookkeeping upon deletion, I am leaning towards skipping it. On use cases where one adds and deletes a lot of documents, if cleaning up garbage is a concern, one could always re-index the whole collection after a certain number of deletions is reached, and then "hot swap" the MiniSearch instance in use for search. My feeling is that it is worth documenting it, but not to add complex bookkeeping logic.

Now I just need to decide whether to make two major releases (one for this PR, one for further serialization changes), or whether to finally implement the serialization changes and release all in a single major release. In most of my production use-cases I also do not use index serialization, but there are users who rely on that, and there is for example a library out there to serialize the index in Rust, which would be annoying for the author to re-implement twice.

I will immediately release your other PR with a minor version bump though.

2022-02-16 10:59 UTC, rolftimmermans commented
> Now I just need to decide whether to make two major releases (one for this PR, one for further serialization changes), or whether to finally implement the serialization changes and release all in a single major release. In most of my production use-cases I also do not use index serialization, but there are users who rely on that, and there is for example a library out there to serialize the index in Rust, which would be annoying for the author to re-implement twice.

It does make sense to give the serialisation format some more thought and to settle on a reasonable format that decouples it from the internal representation _before_ releasing breaking changes.

An alternative to consider is to spend some effort in removing the backwards incompatibility of the serialisation format in this PR (which means transforming the arrays with field lengths to/from objects). But that's probably only worthwhile if a new serialisation format is unlikely to be worked on by you or someone else soon. What do you think?

2022-02-16 11:05 UTC, lucaong commented
Yeah at the moment I think that serializing an array of postings should be reasonably simple to do. I will give it a try in the next days, and if successful, we can release these changes in a single major version. If it proves to be challenging, I can let you know here and in case work to make this PR backward compatible.

2022-02-16 14:52 UTC, lucaong commented
Ok, I created a pull request that makes the serialization format more abstract. I might still retouch it a bit, for example to warn users if they mistakenly try to pass a serialized index made in a different version, and maybe adding a serialization version number to make that easier in the future, but for the rest it should be final.

The `index` field of the serialized structure is now an array of `[term, termData]` tuples, instead of being the raw internals of the radix tree.

I tested combining that with your changes on [this branch](https://github.com/lucaong/minisearch/tree/test_merge_122_and_abstract_serialization), and the result is not slower than your version, again roughly 40% slower than the previous deserialization logic. I think that's acceptable, given all the other benefits. [This commit](https://github.com/lucaong/minisearch/commit/17be8c0a8f5de4bb8b9651300d91c90687295800) is the one to cherry-pick once the new serialization format is merged to master. As you can see, it even makes the `objectToTree` and `treeToObject` functions obsolete.

2022-02-16 16:58 UTC, rolftimmermans commented
> As you can see, it even makes the objectToTree and treeToObject functions obsolete.
Great! Those were the gnarliest!

2022-02-17 08:37 UTC, rolftimmermans commented
FYI, I've added a few commits with some (modest) improvements.

2022-02-17 09:08 UTC, lucaong requested changes
Just one comment about a deprecation, for the rest it looks great. The functional style is replaced, but the code still remains readable, and the performance gain is large enough to justify it (especially indexing).

Thanks a lot!

2022-02-17 09:08 UTC, lucaong commented on src/SearchableMap/SearchableMap.ts
> +   * @deprecated Use a `for (... of ...)` loop instead.
I would not deprecate `forEach`, because `SearchableMap` is exposed as its own module for users who need to directly use it. Since `SearchableMap` should support the same API as `Map` (plus prefix/fuzzy search, minus being restricted to string keys), the `forEach` method should be there (even if we choose not to use it in `MiniSearch`).

2022-02-17 09:41 UTC, lucaong approved these changes

2022-02-17 09:41 UTC, merged